@startuml

BinaryTree <|-- BinarySearchTree
BinaryTree <|-- RightSingleThreadedBinaryTree
BinaryTree <|-- LeftSingleThreadedBinaryTree
BinaryTree <|-- DoubleThreadedBinaryTree
BinaryTree <|-- RBTree
BinaryTree <|-- AVLTree

class BinaryTree {
    +root: NodeType
    +empty: bool
    {abstract} +search()
    {abstract} +insert()
    {abstract} +delete()
    {abstract} +get_leftmost()
    {abstract} +get_rightmost()
    {abstract} +get_successor()
    {abstract} +get_predecessor()
    {abstract} +get_height()
}

class BinarySearchTree {
    -_transplant()
}

class RightSingleThreadedBinaryTree {
    +inorder_traverse()
    +preorder_traverse()
    -_transplant()
}

class LeftSingleThreadedBinaryTree {
    +reverse_inorder_traverse()
    -_transplant()
}

class DoubleThreadedBinaryTree {
    +inorder_traverse()
    +preorder_traverse()
    +reverse_inorder_traverse()
    -_transplant()
}

class RBTree {
    +inorder_traverse()
    +preorder_traverse()
    +postorder_traverse()
    -_left_rotate()
    -_right_rotate()
    -_insert_fixup()
    -_delete_fixup()
    -_inorder_traverse()
    -_preorder_traverse()
    -_postorder_traverse()
    -_transplant()

}

class AVLTree {
    -_left_rotate()
    -_right_rotate()
    -_balance_factor()
    -_delete_fixup()
    -_transplant()
}


@enduml
