@startuml

Node <|-- SingleThreadNode
Node <|-- DoubleThreadNode
Node <|-- RBNode
Node <|-- AVLNode

class Node {
    +key: any comparable type
    +data: Any
    +left: NodeType
    +right: NodeType
    +parent: NodeType
}

class SingleThreadNode {
    +is_thread: bool
}

class DoubleThreadNode {
    +is_left_thread: bool
    +is_right_thread: bool
}

class RBNode {
    +color: Red or Black
}

class AVLNode {
    +height: int
}


@enduml
