name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Format with black
      uses: psf/black@stable
    - name: Linting with flake8
      run: flake8 **/*.py
    - name: Type checking with mypy
      run: mypy **/*.py
    - name: Docstring check with pydocstyle
      run: pydocstyle
